name: Docker Build and Push

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build Docker image for'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: registry.cn-qingdao.aliyuncs.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t registry.cn-qingdao.aliyuncs.com/eo/mongo-shake:${{ github.event.inputs.tag }} .
          docker tag registry.cn-qingdao.aliyuncs.com/eo/mongo-shake:${{ github.event.inputs.tag }} registry.cn-qingdao.aliyuncs.com/eo/mongo-shake:latest
      
      - name: Push Docker image
        run: |
          docker push registry.cn-qingdao.aliyuncs.com/eo/mongo-shake:${{ github.event.inputs.tag }}
          docker push registry.cn-qingdao.aliyuncs.com/eo/mongo-shake:latest
