name: Docker Build and Push

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: registry.cn-qingdao.aliyuncs.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Determine Git Tag
        id: git_tag
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/*/}

      - name: Build Docker image
        run: |
          docker build -t registry.cn-qingdao.aliyuncs.com/eo/mongo-shake:${{ steps.git_tag.outputs.TAG }} .
          docker tag registry.cn-qingdao.aliyuncs.com/eo/mongo-shake:${{ steps.git_tag.outputs.TAG }} registry.cn-qingdao.aliyuncs.com/eo/mongo-shake:latest
      
      - name: Push Docker image
        run: |
          docker push registry.cn-qingdao.aliyuncs.com/eo/mongo-shake:${{ steps.git_tag.outputs.TAG }}
          docker push registry.cn-qingdao.aliyuncs.com/eo/mongo-shake:latest
